name: Sync with Azure DevOps

on:
  issues:
    types: [opened]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Testing workflow
    steps:       
    - uses: actions/checkout@v3
    - uses: a11smiles/GitSync@main
      env:     
        ado : {
          token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        }
        github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        config_file: './.github/workflows/gsconfig.json'